-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: extensions/PageCheckout/db/page_checkout_locks_index.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TEMPORARY TABLE /*_*/__temp__page_checkout_locks AS
SELECT
  pcl_id,
  pcl_page_id,
  pcl_user_id,
  pcl_payload
FROM /*_*/page_checkout_locks;
DROP TABLE /*_*/page_checkout_locks;


CREATE TABLE /*_*/page_checkout_locks (
    pcl_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    pcl_page_id INTEGER NOT NULL, pcl_user_id INTEGER NOT NULL,
    pcl_payload BLOB DEFAULT NULL
  );
INSERT INTO /*_*/page_checkout_locks (
    pcl_id, pcl_page_id, pcl_user_id,
    pcl_payload
  )
SELECT
  pcl_id,
  pcl_page_id,
  pcl_user_id,
  pcl_payload
FROM
  /*_*/__temp__page_checkout_locks;
DROP TABLE /*_*/__temp__page_checkout_locks;

CREATE INDEX pcl_page_id_user_id_index ON /*_*/page_checkout_locks (pcl_page_id, pcl_user_id);
