-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: db/page_checkout_locks.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/page_checkout_locks (
  pcl_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  pcl_page_id INTEGER NOT NULL, pcl_user_id INTEGER NOT NULL,
  pcl_payload BLOB DEFAULT NULL
);
