-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: db/page_checkout_event.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/page_checkout_event (
  pce_action BLOB NOT NULL, pce_actor_id INTEGER NOT NULL,
  pce_page_id INTEGER NOT NULL, pce_revision_id INTEGER NOT NULL,
  pce_timestamp BLOB DEFAULT NULL, pce_comment CLOB DEFAULT NULL,
  pce_lock BLOB DEFAULT NULL
);
