-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: extensions/PageCheckout/db/page_checkout_locks_index.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE INDEX pcl_page_id_user_id_index ON /*_*/page_checkout_locks (pcl_page_id, pcl_user_id);
