-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/PageCheckout/db/page_checkout_locks.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/page_checkout_locks (
  pcl_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  pcl_page_id INT NOT NULL,
  pcl_user_id INT NOT NULL,
  pcl_payload LONGBLOB DEFAULT NULL,
  INDEX pcl_page_id_user_id_index (pcl_page_id, pcl_user_id),
  PRIMARY KEY(pcl_id)
) /*$wgDBTableOptions*/;
