-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: db/page_checkout_locks.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE page_checkout_locks (
  pcl_id SERIAL NOT NULL,
  pcl_page_id INT NOT NULL,
  pcl_user_id INT NOT NULL,
  pcl_payload TEXT DEFAULT NULL,
  PRIMARY KEY(pcl_id)
);
